
#_____________________________________________Livingroom Sensor____________________________________________________
- platform: mqtt  
  state_topic: "fl2/livingroom"  
  name: "2fl Livingroom Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "fl2/livingroom"  
  name: "2fl Livingroom LDR"
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
  
- platform: mqtt  
  state_topic: "fl2/livingroom"  
  name: "2fl Livingroom PIR"  
  value_template: '{{ value_json.motion }}'  
  
- platform: mqtt  
  state_topic: "fl2/livingroom"  
  name: "2fl Livingroom Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "fl2/livingroom"
  name: "2fl Livingroom Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "fl2/livingroom"
  name: "2fl livingroom Signal"
  unit_of_measurement: "db"
  value_template: '{{ value_json.signal_strength | round(1) }}'
  
#____________________________________________ Masterbedroom _______________________________________________________
#- platform: mqtt  
#  state_topic: "fl2/masterbedroom"  
#  name: "Master Bedroom Humidity"  
#  unit_of_measurement: "%"  
#  value_template: '{{ value_json.humidity | round(1) }}'  
  
#- platform: mqtt  
#  state_topic: "fl2/masterbedroom"  
#  name: "Master Bedroom LDR"
#  unit_of_measurement: "LUX"  
#  value_template: '{{ value_json.ldr }}'  
  
#- platform: mqtt  
#  state_topic: "fl2/masterbedroom"  
#  name: "Master Bedroom PIR"  
#  value_template: '{{ value_json.motion }}'  
  
#- platform: mqtt  
#  state_topic: "fl2/masterbedroom"  
#  name: "Master Bedroom Temperature"  
#  unit_of_measurement: "°F"  
#  value_template: '{{ value_json.temperature | round(1) }}'  

#- platform: mqtt
#  state_topic: "fl2/masterbedroom"
#  name: "Master Bedroom Real Feel"
#  unit_of_measurement: "°F"
#  value_template: '{{ value_json.heatIndex | round(1) }}'

#- platform: mqtt
#  state_topic: "fl2/masterbedroom"
#  name: "Master Bedroom Signal"
#  unit_of_measurement: "db"
#  value_template: '{{ value_json.signal_strength | round(1) }}'

# __________________________________________________Master Bathroom_______________________________________________ 
- platform: mqtt  
  state_topic: "tele/masterbathroom/sensor"  
  name: "Master Bathroom Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "tele/masterbathroom/sensor"  
  name: "Master Bathroom LDR"
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
  
- platform: mqtt  
  state_topic: "tele/masterbathroom/sensor"  
  name: "Master Bathroom PIR"  
  value_template: '{{ value_json.motion }}'  
  
- platform: mqtt  
  state_topic: "tele/masterbathroom/sensor"  
  name: "Master Bathroom Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "tele/masterbathroom/sensor"
  name: "Master Bathroom Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'
  
- platform: mqtt
  state_topic: "tele/masterbathroom/sensor"
  name: "Master Bathroom Signal"
  unit_of_measurement: "db"
  value_template: '{{ value_json.signal_strength | round(1) }}'


# ________________________________________________________________Kitchen__________________________________________________________
- platform: mqtt  
  state_topic: "tele/kitchen/sensor"  
  name: "Upstairs Kitchen Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "tele/kitchen/sensor"  
  name: "Upstairs Kitchen LDR"
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
  
- platform: mqtt  
  state_topic: "tele/kitchen/sensor"  
  name: "Upstairs Kitchen PIR"  
  value_template: '{{ value_json.motion }}'  
  
- platform: mqtt  
  state_topic: "tele/kitchen/sensor"  
  name: "Upstairs Ktchen Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "tele/kitchen/sensor"
  name: "Upstairs Kitchen Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "tele/kitchen/sensor"
  name: "Upstairs Kitchen Signal"
  unit_of_measurement: "db"
  value_template: '{{ value_json.signal_strength | round(1) }}'

# __________________________________________Downstairs Kitchen________________________________________________________
- platform: mqtt  
  state_topic: "tele/downstairskitchen/sensor"  
  name: "Downstairs Kitchen Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "tele/downstairskitchen/sensor"  
  name: "Downstairs Kitchen LDR"
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
  
- platform: mqtt  
  state_topic: "tele/downstairskitchen/sensor"  
  name: "Downstairs Kitchen PIR"  
  value_template: '{{ value_json.motion }}'  
  
- platform: mqtt  
  state_topic: "tele/downstairskitchen/sensor"  
  name: "Downstairs Ktchen Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "tele/downstairskitchen/sensor"
  name: "Downstairs Kitchen Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "tele/downstairskitchen/sensor"
  name: "Downstairs Kitchen Signal"
  unit_of_measurement: "db"
  value_template: '{{ value_json.signal_strength | round(1) }}'

# ____________________________________________________________________Outside_________________________________________________________
- platform: mqtt  
  state_topic: "tele/outside/sensor"  
  name: "outside Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "tele/outside/sensor"  
  name: "outside LDR"
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
  
- platform: mqtt  
  state_topic: "tele/outside/sensor"  
  name: "outside Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "tele/outside/sensor"
  name: "outside Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'
  
- platform: mqtt
  state_topic: "tele/outside/sensor"
  name: "Outside Signal"
  unit_of_measurement: "db"
  value_template: '{{ value_json.signal_strength | round(1) }}'

- platform: yr
#_______________________________________________washing machine and dryer________________________________________________
- platform: mqtt
  name: "Washer State"
  state_topic: "hass/state/washer"
  icon: mdi:washing-machine

- platform: mqtt
  name: "Dryer State"
  state_topic: "hass/state/dryer"
  icon: mdi:tumble-dryer

- platform: mqtt
  name: "Washer Watts"
  state_topic: "tele/washing_machine/SENSOR"
  value_template: "{{value_json['ENERGY'].Power }}"
  qos: 2
  unit_of_measurement: "W"
  icon: mdi:flash-circle
  availability_topic: "tele/washing_machine/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  state_topic: "tele/washing_machine/STATE"
  name: "washer Signal"
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/washing_machine/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Washer Voltage"
  state_topic: "tele/washing_machine/SENSOR"
  value_template: "{{value_json['ENERGY'].Voltage }}"
  qos: 2
  unit_of_measurement : "V"
  icon: mdi:flash-circle
  availability_topic: "tele/washing_machine/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Washer Amps"
  state_topic: "tele/washing_machine/SENSOR"
  value_template: "{{value_json['ENERGY'].Current }}"
  qos: 2
  unit_of_measurement : "A"
  icon: mdi:flash-circle
  availability_topic: "tele/washing_machine/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "Washer Energy Today"
  state_topic: "tele/washing_machine/SENSOR"
  value_template: "{{value_json['ENERGY'].Today }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/washing_machine/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Washer Energy Yesterday"
  state_topic: "tele/washing_machine/SENSOR"
  value_template: "{{value_json['ENERGY'].Yesterday }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/washing_machine/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

#------------------------Christmas Lights------------------------------------------------

- platform: mqtt
  name: "Lights Watts"
  state_topic: "tele/christmas lights/SENSOR"
  value_template: "{{value_json['ENERGY'].Power }}"
  qos: 2
  unit_of_measurement: "W"
  icon: mdi:flash-circle
  availability_topic: "tele/christmas lights/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  state_topic: "tele/christmas lights/STATE"
  name: "Lights Signal"
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/christmas lights/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Lights Voltage"
  state_topic: "tele/christmas lights/SENSOR"
  value_template: "{{value_json['ENERGY'].Voltage }}"
  qos: 2
  unit_of_measurement : "V"
  icon: mdi:flash-circle
  availability_topic: "tele/christmas lights/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Lights Amps"
  state_topic: "tele/christmas lights/SENSOR"
  value_template: "{{value_json['ENERGY'].Current }}"
  qos: 2
  unit_of_measurement : "A"
  icon: mdi:flash-circle
  availability_topic: "tele/christmas lights/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "Energy Today"
  state_topic: "tele/christmas lights/SENSOR"
  value_template: "{{value_json['ENERGY'].Today }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/christmas lights/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Energy Yesterday"
  state_topic: "tele/christmas lights/SENSOR"
  value_template: "{{value_json['ENERGY'].Yesterday }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/christmas lights/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

#--------------------------3D Printer-------------------------------------------------
- platform: mqtt
  name: "Printer State"
  state_topic: "hass/state/printer"
  

- platform: mqtt
  name: "3D Printer Watts"
  state_topic: "tele/3d_printer/SENSOR"
  value_template: "{{value_json['ENERGY'].Power }}"
  qos: 2
  unit_of_measurement: "W"
  icon: mdi:flash-circle
  availability_topic: "tele/3d_printer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  state_topic: "tele/3d_printer/STATE"
  name: "3D Printer Signal"
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/3d_printer/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "3D Printer Voltage"
  state_topic: "tele/3d_printer/SENSOR"
  value_template: "{{value_json['ENERGY'].Voltage }}"
  qos: 2
  unit_of_measurement : "V"
  icon: mdi:flash-circle
  availability_topic: "tele/3d_printer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "3D Printer Amps"
  state_topic: "tele/3d_printer/SENSOR"
  value_template: "{{value_json['ENERGY'].Current }}"
  qos: 2
  unit_of_measurement : "A"
  icon: mdi:flash-circle
  availability_topic: "tele/3d_printer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "3D Printer Energy Today"
  state_topic: "tele/3d_printer/SENSOR"
  value_template: "{{value_json['ENERGY'].Today }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/3d_printer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "3D Printer Energy Yesterday"
  state_topic: "tele/3d_printer/SENSOR"
  value_template: "{{value_json['ENERGY'].Yesterday }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/3d_printer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

#-----------------------------------Master Bathroom Sink Light--------------------------------------------

- platform: mqtt
  name: "Master Bathroom Sink Light Watts"
  state_topic: "tele/master_bathroom_sink_light/SENSOR"
  value_template: "{{value_json['ENERGY'].Power }}"
  qos: 2
  unit_of_measurement: "W"
  icon: mdi:flash-circle
  availability_topic: "tele/master_bathroom_sink_light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  state_topic: "tele/master_bathroom_sink_light/STATE"
  name: "Master Bathroom Sink Light Signal"
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/master_bathroom_sink_light/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Master Bathroom Sink Light Voltage"
  state_topic: "tele/master_bathroom_sink_light/SENSOR"
  value_template: "{{value_json['ENERGY'].Voltage }}"
  qos: 2
  unit_of_measurement : "V"
  icon: mdi:flash-circle
  availability_topic: "tele/master_bathroom_sink_light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Master Bathroom Sink Light Amps"
  state_topic: "tele/master_bathroom_sink_light/SENSOR"
  value_template: "{{value_json['ENERGY'].Current }}"
  qos: 2
  unit_of_measurement : "A"
  icon: mdi:flash-circle
  availability_topic: "tele/master_bathroom_sink_light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "Master Bathroom Sink Light Today"
  state_topic: "tele/master_bathroom_sink_light/SENSOR"
  value_template: "{{value_json['ENERGY'].Today }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/master_bathroom_sink_light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Master Bathroom Sink Light Energy Yesterday"
  state_topic: "tele/master_bathroom_sink_light/SENSOR"
  value_template: "{{value_json['ENERGY'].Yesterday }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/master_bathroom_sink_light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

#-------------------------------------------------Brittney's lamp -----------------------------------------------

- platform: mqtt
  state_topic: "tele/lamp2/STATE"
  name: "Brittney's Lamp Signal"
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/lamp2/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

#-----------------------------------------------Amber's lamp ---------------------------------------------

- platform: mqtt
  state_topic: "tele/lamp1/STATE"
  name: "Amber's Lamp Signal"
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/lamp1/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

#------------------------------------------------youtube sensors ---------------------------------------
- platform: youtube
  channel_id: UC7G4tLa4Kt6A9e3hJ-HO8ng
- platform: youtube
  channel_id: UC5ZdPKE2ckcBhljTc2R_qNA
- platform: youtube
  channel_id: UC2gyzKcHbYfqoXA5xbyGXtQ


